services:
  - type: web
    name: shadow-goose-api-staging
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: CORS_ORIGINS
        value: https://shadow-goose-web-staging.onrender.com
      - key: SENTRY_DSN
        sync: false
      - key: REDIS_URL
        sync: false
    healthCheckPath: /health

  - type: web
    name: shadow-goose-web-staging
    env: node
    plan: starter
    buildCommand: cd frontend && npm ci && npm run build
    startCommand: cd frontend/.next/standalone && PORT=$PORT node server.js
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://shadow-goose-api-staging.onrender.com
      - key: NEXT_PUBLIC_CLIENT
        value: shadow-goose
      - key: NEXT_PUBLIC_APP_NAME
        value: Shadow Goose Entertainment (Staging)
      - key: NEXT_PUBLIC_APP_VERSION
        value: 1.0.0
      - key: NEXT_PUBLIC_ENV
        value: staging
    healthCheckPath: /api/health 