services:
  - type: web
    name: shadow-goose-api
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: shadow-goose-db
          property: connectionString
      - key: SECRET_KEY
        value: shadow-goose-secret-key-2025-production-xyz789
      - key: JWT_SECRET_KEY
        value: shadow-goose-jwt-secret-2025-production-abc123
      - key: CORS_ORIGINS
        value: https://shadow-goose-web.onrender.com
      - key: SENTRY_DSN
        value: https://shadow-goose-sentry-dsn-2025
      - key: REDIS_URL
        value: redis://shadow-goose-redis:6379
    healthCheckPath: /health

  - type: web
    name: shadow-goose-web
    env: node
    plan: starter
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://shadow-goose-api.onrender.com
      - key: NEXT_PUBLIC_CLIENT
        value: shadow-goose
      - key: NEXT_PUBLIC_APP_NAME
        value: Shadow Goose Entertainment
      - key: NEXT_PUBLIC_APP_VERSION
        value: 1.0.0
      - key: NEXT_PUBLIC_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true
    branch: main

databases:
  - name: shadow-goose-db
    databaseName: shadow_goose_prod
    user: shadow_goose_user
    plan: starter
