services:
  - type: web
    name: shadow-goose-api-staging
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        value: postgresql://final_goose_db_user:MII5440GTcgWHUGHCTWP2F0mo8SQ4Xg3@dpg-d2apq1h5pdvs73c2gbog-a/final_goose_db
      - key: SECRET_KEY
        value: shadow-goose-secret-key-2025-staging
      - key: JWT_SECRET_KEY
        value: shadow-goose-jwt-secret-2025-staging
      - key: CORS_ORIGINS
        value: https://shadow-goose-web-staging.onrender.com
      - key: SENTRY_DSN
        sync: false
      - key: REDIS_URL
        sync: false
    healthCheckPath: /health

  - type: web
    name: shadow-goose-web-staging
    env: node
    plan: starter
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://shadow-goose-api-staging.onrender.com
      - key: NEXT_PUBLIC_CLIENT
        value: shadow-goose
      - key: NEXT_PUBLIC_APP_NAME
        value: Shadow Goose Entertainment (Staging)
      - key: NEXT_PUBLIC_APP_VERSION
        value: 1.0.0
      - key: NEXT_PUBLIC_ENV
        value: staging
    healthCheckPath: /api/health 