name: SGE Delivery Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      week:
        description: 'SGE Week to check (1, 2, 3, or 4)'
        required: false
        default: '1'

jobs:
  sge-week-1-check:
    runs-on: ubuntu-latest
    name: SGE Week 1 - Core Functionality
    if: github.event.inputs.week == '1' || github.event.inputs.week == '' || github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          if [ -f "package.json" ]; then
            npm ci
          fi
          if [ -f "requirements.txt" ]; then
            pip install -r requirements.txt
          fi

      - name: SGE JWT Authentication Check
        run: |
          echo "🔒 Checking SGE JWT authentication..."
          if grep -r "jwt\|JWT" . --include="*.py" --include="*.js" --include="*.ts" | grep -q "import\|require"; then
            echo "✅ SGE JWT authentication found"
          else
            echo "❌ SGE JWT authentication missing - CRITICAL for Week 1"
            exit 1
          fi

      - name: SGE Project Baseline Check
        run: |
          echo "📊 Checking SGE project baseline capture..."
          if grep -r "project\|baseline" . --include="*.py" --include="*.js" --include="*.ts" | grep -q "model\|schema"; then
            echo "✅ SGE project baseline system found"
          else
            echo "❌ SGE project baseline system missing - CRITICAL for Week 1"
            exit 1
          fi

      - name: SGE Dashboard Check
        run: |
          echo "📈 Checking SGE impact dashboard..."
          if [ -f "package.json" ]; then
            npm run build
            echo "✅ SGE dashboard build successful"
          else
            echo "❌ SGE dashboard missing - CRITICAL for Week 1"
            exit 1
          fi

      - name: SGE Mobile Responsiveness Check
        run: |
          echo "📱 Checking SGE mobile responsiveness..."
          if grep -r "mobile\|responsive" . --include="*.css" --include="*.scss" --include="*.tsx" | grep -q "media\|flex\|grid"; then
            echo "✅ SGE mobile responsiveness found"
          else
            echo "⚠️ SGE mobile responsiveness may need improvement"
          fi

      - name: SGE Branding Check
        run: |
          echo "🎨 Checking SGE branding..."
          if [ -f "public/logo.png" ] || [ -f "src/assets/logo.png" ] || grep -r "SGE\|brand" . --include="*.tsx" --include="*.js" | grep -q "SGE"; then
            echo "✅ SGE branding elements found"
          else
            echo "⚠️ SGE branding may need enhancement"
          fi

  sge-week-2-check:
    runs-on: ubuntu-latest
    name: SGE Week 2 - Data & Reporting
    if: github.event.inputs.week == '2'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SGE OKR System Check
        run: |
          echo "🎯 Checking SGE OKR system..."
          if grep -r "OKR\|okr\|objective" . --include="*.py" --include="*.js" --include="*.ts" | grep -q "model\|schema"; then
            echo "✅ SGE OKR system found"
          else
            echo "❌ SGE OKR system missing - CRITICAL for Week 2"
            exit 1
          fi

      - name: SGE Real-time Updates Check
        run: |
          echo "⚡ Checking SGE real-time updates..."
          if grep -r "real-time\|websocket\|live" . --include="*.py" --include="*.js" --include="*.ts" | grep -q "import\|require"; then
            echo "✅ SGE real-time updates found"
          else
            echo "⚠️ SGE real-time updates may need implementation"
          fi

      - name: SGE Reporting Check
        run: |
          echo "📊 Checking SGE reporting capabilities..."
          if grep -r "report\|export\|pdf" . --include="*.py" --include="*.js" --include="*.ts" | grep -q "import\|require"; then
            echo "✅ SGE reporting capabilities found"
          else
            echo "❌ SGE reporting capabilities missing - CRITICAL for Week 2"
            exit 1
          fi

      - name: SGE User Management Check
        run: |
          echo "👥 Checking SGE user management..."
          if grep -r "user\|role\|permission" . --include="*.py" --include="*.js" --include="*.ts" | grep -q "model\|schema"; then
            echo "✅ SGE user management found"
          else
            echo "❌ SGE user management missing - CRITICAL for Week 2"
            exit 1
          fi

  sge-week-3-check:
    runs-on: ubuntu-latest
    name: SGE Week 3 - Evidence Capture
    if: github.event.inputs.week == '3'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SGE Story Capture Check
        run: |
          echo "📝 Checking SGE story capture..."
          if grep -r "story\|narrative\|qualitative" . --include="*.py" --include="*.js" --include="*.ts" | grep -q "model\|schema"; then
            echo "✅ SGE story capture found"
          else
            echo "❌ SGE story capture missing - CRITICAL for Week 3"
            exit 1
          fi

      - name: SGE Photo Upload Check
        run: |
          echo "📸 Checking SGE photo upload..."
          if grep -r "upload\|file\|image\|photo" . --include="*.py" --include="*.js" --include="*.ts" | grep -q "import\|require"; then
            echo "✅ SGE photo upload found"
          else
            echo "❌ SGE photo upload missing - CRITICAL for Week 3"
            exit 1
          fi

      - name: SGE Stakeholder Feedback Check
        run: |
          echo "💬 Checking SGE stakeholder feedback..."
          if grep -r "feedback\|stakeholder\|comment" . --include="*.py" --include="*.js" --include="*.ts" | grep -q "model\|schema"; then
            echo "✅ SGE stakeholder feedback found"
          else
            echo "❌ SGE stakeholder feedback missing - CRITICAL for Week 3"
            exit 1
          fi

      - name: SGE Attribution Check
        run: |
          echo "📊 Checking SGE attribution tracking..."
          if grep -r "attribution\|contribution\|percentage" . --include="*.py" --include="*.js" --include="*.ts" | grep -q "model\|schema"; then
            echo "✅ SGE attribution tracking found"
          else
            echo "❌ SGE attribution tracking missing - CRITICAL for Week 3"
            exit 1
          fi

  sge-week-4-check:
    runs-on: ubuntu-latest
    name: SGE Week 4 - Reporting Excellence
    if: github.event.inputs.week == '4'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SGE PDF Reports Check
        run: |
          echo "📄 Checking SGE PDF reports..."
          if grep -r "pdf\|report\|export" . --include="*.py" --include="*.js" --include="*.ts" | grep -q "import\|require"; then
            echo "✅ SGE PDF reports found"
          else
            echo "❌ SGE PDF reports missing - CRITICAL for Week 4"
            exit 1
          fi

      - name: SGE Impact Metrics Check
        run: |
          echo "📈 Checking SGE impact metrics..."
          if grep -r "metric\|impact\|measurement" . --include="*.py" --include="*.js" --include="*.ts" | grep -q "model\|schema"; then
            echo "✅ SGE impact metrics found"
          else
            echo "❌ SGE impact metrics missing - CRITICAL for Week 4"
            exit 1
          fi

      - name: SGE Dashboard Improvements Check
        run: |
          echo "📊 Checking SGE dashboard improvements..."
          if [ -f "package.json" ]; then
            npm run build
            echo "✅ SGE dashboard improvements successful"
          else
            echo "❌ SGE dashboard improvements missing - CRITICAL for Week 4"
            exit 1
          fi

      - name: SGE Data Validation Check
        run: |
          echo "✅ Checking SGE data validation..."
          if grep -r "validation\|verify\|check" . --include="*.py" --include="*.js" --include="*.ts" | grep -q "import\|require"; then
            echo "✅ SGE data validation found"
          else
            echo "❌ SGE data validation missing - CRITICAL for Week 4"
            exit 1
          fi

  sge-delivery-summary:
    runs-on: ubuntu-latest
    name: SGE Delivery Summary
    needs: [sge-week-1-check, sge-week-2-check, sge-week-3-check, sge-week-4-check]
    if: always()
    steps:
      - name: Generate SGE Progress Report
        run: |
          echo "🎯 SGE Delivery Progress Report"
          echo "==============================="
          echo "Generated: $(date)"
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref_name }}"
          echo ""

          echo "🚀 SGE Week 1 - Core Functionality"
          echo "Status: ${{ needs.sge-week-1-check.result }}"
          echo "Critical: JWT, Baselines, Dashboard, Mobile, Branding"
          echo ""

          echo "📊 SGE Week 2 - Data & Reporting"
          echo "Status: ${{ needs.sge-week-2-check.result }}"
          echo "Critical: OKRs, Real-time, Reports, User Management"
          echo ""

          echo "📸 SGE Week 3 - Evidence Capture"
          echo "Status: ${{ needs.sge-week-3-check.result }}"
          echo "Critical: Stories, Photos, Feedback, Attribution"
          echo ""

          echo "📄 SGE Week 4 - Reporting Excellence"
          echo "Status: ${{ needs.sge-week-4-check.result }}"
          echo "Critical: PDF Reports, Metrics, Dashboard, Validation"
          echo ""

          echo "🛡️ SGE Safety Systems"
          echo "- Direct deployment: ✅ Active"
          echo "- Quick rollback: ✅ Available"
          echo "- Automated checks: ✅ Running"
          echo ""

          echo "📋 SGE Next Steps:"
          echo "1. Complete Week 1 critical items"
          echo "2. Deploy to SGE team for testing"
          echo "3. Gather feedback and iterate"
          echo "4. Move to Week 2 implementation"

      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            const week1Status = '${{ needs.sge-week-1-check.result }}';
            const week2Status = '${{ needs.sge-week-2-check.result }}';
            const week3Status = '${{ needs.sge-week-3-check.result }}';
            const week4Status = '${{ needs.sge-week-4-check.result }}';

            const comment = `## 🎯 SGE Delivery Progress

            **Week 1 - Core Functionality**: ${week1Status}
            **Week 2 - Data & Reporting**: ${week2Status}
            **Week 3 - Evidence Capture**: ${week3Status}
            **Week 4 - Reporting Excellence**: ${week4Status}

            **SGE Safety Systems**: ✅ All Active

            This PR supports SGE delivery goals. Keep focused on critical path items! 🚀`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
