name: Syntax Check & Auto-Fix

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  syntax-check:
    runs-on: ubuntu-latest
    name: Syntax Check & Auto-Fix
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Python tools
        run: |
          python -m pip install --upgrade pip
          pip install black flake8 mypy isort

      - name: Install Node.js dependencies
        run: |
          if [ -f "package.json" ]; then
            npm ci
          fi

      - name: Install Python dependencies
        run: |
          if [ -f "requirements.txt" ]; then
            pip install -r requirements.txt
          fi

      - name: Check Python syntax
        run: |
          echo "🔍 Checking Python syntax..."

          # Check for syntax errors
          if [ -f "app/main.py" ]; then
            python -m py_compile app/main.py
            echo "✅ Python main.py syntax check passed"
          fi

          # Check all Python files
          find . -name "*.py" -not -path "./venv/*" -not -path "./.venv/*" -exec python -m py_compile {} \;
          echo "✅ All Python files syntax check passed"

      - name: Check TypeScript syntax
        run: |
          if [ -f "package.json" ]; then
            echo "🔍 Checking TypeScript syntax..."

            # Type check
            npm run type-check || {
              echo "❌ TypeScript syntax errors found"
              exit 1
            }

            # Lint check
            npm run lint || {
              echo "❌ TypeScript linting errors found"
              exit 1
            }

            echo "✅ TypeScript syntax check passed"
          fi

      - name: Run auto-fix script
        if: failure()
        run: |
          echo "🔧 Running auto-fix script..."

          # Make script executable
          chmod +x WHITE_LABEL_UPDATED/scripts/auto-fix-syntax.js

          # Run auto-fix
          node WHITE_LABEL_UPDATED/scripts/auto-fix-syntax.js || {
            echo "⚠️ Auto-fix script failed, trying manual fixes..."

            # Manual Python fixes
            if [ -f "requirements.txt" ]; then
              black . || true
              isort . || true
            fi

            # Manual TypeScript fixes
            if [ -f "package.json" ]; then
              npm run lint -- --fix || true
              npx prettier --write "**/*.{ts,tsx,js,jsx,json}" || true
            fi
          }

      - name: Verify fixes
        if: failure()
        run: |
          echo "🔍 Verifying fixes..."

          # Check Python syntax again
          if [ -f "app/main.py" ]; then
            python -m py_compile app/main.py
            echo "✅ Python syntax fixed"
          fi

          # Check TypeScript syntax again
          if [ -f "package.json" ]; then
            npm run type-check || {
              echo "❌ TypeScript syntax still has errors"
              exit 1
            }
            echo "✅ TypeScript syntax fixed"
          fi

      - name: Commit fixes
        if: failure()
        run: |
          echo "📝 Committing auto-fixes..."

          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          # Add all changes
          git add .

          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "🔧 Auto-fix syntax errors

            - Fixed TypeScript syntax errors
            - Fixed Python syntax errors
            - Applied code formatting
            - Resolved linting issues

            Auto-fixed by GitHub Actions syntax check workflow"

            # Push changes
            git push
            echo "✅ Auto-fixes committed and pushed"
          fi

      - name: Report status
        if: always()
        run: |
          echo "📊 Syntax Check Summary"
          echo "======================"
          echo "Status: ${{ job.status }}"
          echo ""
          echo "Checks performed:"
          echo "- Python syntax validation"
          echo "- TypeScript syntax validation"
          echo "- Code formatting"
          echo "- Linting"
          echo ""

          if [ "${{ job.status }}" == "success" ]; then
            echo "🎉 All syntax checks passed!"
          else
            echo "⚠️ Some syntax issues were found and auto-fixed"
          fi

      - name: Comment on PR
        if: github.event_name == 'pull_request' && always()
        uses: actions/github-script@v6
        with:
          script: |
            const status = '${{ job.status }}';
            const comment = status === 'success'
              ? '🎉 **Syntax check passed!** No syntax errors found.'
              : '🔧 **Syntax errors were detected and auto-fixed!** The fixes have been committed to your branch.';

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
